name: CI
on:
  push:
    branches:
      - master
# permissions:
#   contents: write
jobs:
  build-and-deploy:
    # æŒ‡å®šæ“ä½œç³»ç»Ÿ
    runs-on: ubuntu-latest
    steps:
      # å°†ä»£ç æ‹‰åˆ°è™šæ‹Ÿæœº
      - name: Checkout repository
        uses: actions/checkout@v3
      # æŒ‡å®šnodeç‰ˆæœ¬
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # ä¾èµ–ç¼“å­˜ç­–ç•¥
      # - name: Cache
      #   id: cache-dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{runner.OS}}-${{hashFiles('**/pnpm-lock.yaml')}}
      - name: Install pnpm
        run: npm install -g pnpm@7.5.0
      # ä¾èµ–ä¸‹è½½
      # - name: Installing Dependencies
      #   if: steps.cache-dependencies.outputs.cache-hit != 'true'
      #   run: pnpm install
      # æ‰“åŒ… & ä¸‹è½½
      - name: Install & Build
        run: |
          pnpm install
          npm run build
      # éƒ¨ç½²
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist